eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
  instance:
    prefer-ip-address: true
    hostname: localhost
spring:
  jackson:
    default-property-inclusion: NON_NULL
  application:
    name: gateway
jwt:
  secret:
    key: secretKey
